apiVersion: v1
kind: Service
metadata:
  name: product-alert-service
spec:
  selector:
    app: product-alert-service-app
  ports:
    - name: product-alert-service
      protocol:
      port: 8083
      targetPort: 8083
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-alert-service-app
spec:
  selector:
    matchLabels:
      app: product-alert-service-app
  replicas: 1
  template:
    metadata:
      labels:
        app: product-alert-service-app
    spec:
      containers:
        - name: product-alert-service-app
          image: ufukhalis/product-alert-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
